services:
  db:
    image: apache/age:latest
    container_name: imdb-age-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: imdb-graph-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: imdb
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: imdb-graph-frontend
    # volumes allow for code changes to reflect in container
    volumes:
      - ./frontend:/app  
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
