services:
  backend:
    build:
      dockerfile: dockerfile.prod
    environment:
      NODE_ENV: production
    restart: always
    volumes: !override
      - ./data:/app/data
    
  frontend:
    build:
      dockerfile: dockerfile.prod
    restart: always
    ports: !override
      - "3000:80"
