services:
  db:
    image: apache/age:latest
    container_name: imdb-age-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: imdb-graph-backend
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: imdb-graph-frontend
    # volumes allow for code changes to reflect in container
    volumes:
      - ./frontend:/app  
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
